service: 
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-3

functions:
  app:
    handler: backend/dist/src/server.handler
    environment:
      NODE_ENV: production
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

include:
  - backend/dist/**/*
  - frontend/**/*
exclude:
  - env.example